### Users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvYmV5IiwiX2lkIjoiNjFiMDlhMmExMGM4NWIyNTBlNTE3ZDQ3IiwiaWF0IjoxNjM4OTYzNzYxfQ.9G4cPVvr2q_23tv9vEoZHZAcI3MLv8P4P8_URiaPvYA

### Profile
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvYmV5IiwiX2lkIjoiNjFiMGE0YTBkOTZjYzIyZGQxYmZlZmU0IiwiaWF0IjoxNjM4OTY2NTg1fQ.01CCtmOSwddcCVWabwITy0ykER0WJlnN7cmCYTvdvYk

### Register
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "Tobey",
    "password": "passfork",
    "mail": "test@test.com"
}

### Login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "Tobey",
    "password": "passfork"
}

### Logout
POST http://localhost:3000/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvYmV5IiwiX2lkIjoiNjFiMGE0YTBkOTZjYzIyZGQxYmZlZmU0IiwiaWF0IjoxNjM4OTY2NTg3fQ.GHQHOVt8JIbzDvXnhL0hLN-n1czvrst5PGEb-q8bycg

### Logout global
POST http://localhost:3000/users/logoutGlobal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvYmV5IiwiX2lkIjoiNjFiMGE0YTBkOTZjYzIyZGQxYmZlZmU0IiwiaWF0IjoxNjM4OTY2NDkyfQ.rSaf9htRxeU2zxqhm8Co1qCg6Vc-psx4No1lceTeAYk
