@host = http://localhost:3000
@token = {{Login.response.body.token}}

###
# @name Users
GET {{host}}/users

###
# @name Profile
GET {{host}}/users/me
Authorization: Bearer {{token}}

###
# @name Remove
DELETE  {{host}}/users/me
Authorization: Bearer {{token}}

###
# @name Register
POST {{host}}/users
Content-Type: application/json

{
    "username": "Tobeyz",
    "password": "passfork",
    "mail": "test@test.comz"
}

###
# @name Update
PATCH {{host}}/users/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "Vasek"
}

###
# @name Login
POST {{host}}/users/login
Content-Type: application/json

{
    "username": "Tobey",
    "password": "passfork"
}

###
# @name Logout
POST {{host}}/users/logout
Authorization: Bearer {{token}}

###
# @name Logout global
POST {{host}}/users/logoutGlobal
Authorization: Bearer {{token}}
